# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20171126_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
