# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_baseuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
