# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20171126_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='USERNAME_FIELD',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
