# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0005_auto_20171126_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
