# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20171128_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='baseuser_ptr',
        ),
    ]
