# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_student_baseuser_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField(auto_now_add=True)),
                ('max_mark', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='max_mark',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.Student'),
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='student',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='education.Exam'),
            preserve_default=False,
        ),
    ]
