# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20171217_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together=set([('exam', 'student')]),
        ),
    ]
