# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20171219_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student_degrees', models.PositiveIntegerField()),
                ('total_max_exam_degrees', models.PositiveIntegerField()),
                ('total_attendance_score', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='education.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='education.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examrecords', to='education.Exam'),
        ),
    ]
