# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20171226_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='total_attendance_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='total_max_exam_degrees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='total_student_degrees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
