# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20171226_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='exams',
            field=models.ManyToManyField(blank=True, to='education.Exam'),
        ),
    ]
