# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_auto_20171226_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='attendances',
            field=models.ManyToManyField(blank=True, to='education.AttendanceRecord'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='examrecrods',
            field=models.ManyToManyField(blank=True, to='education.ExamRecord'),
        ),
    ]
