# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_auto_20171226_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='students', to='education.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together=set([('course', 'student')]),
        ),
    ]
