# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_auto_20180101_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseUser',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', to='education.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(db_index=True, default=education.models.id_generator, max_length=5, primary_key=True, serialize=False),
        ),
    ]
