# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
