# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171126_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='not_useful',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='public.ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='review',
            name='useful',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
